### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by dlxmax** [hanshuebner/mockingboard2k#3]
Hi, I searched the net but couldn't find any references to this project, except for somebody selling pcb's on Ebay, which is how I learned about this.
Does it work? How are you handing the audio output? Are there any changes that need to be made?
Thanks for updating. Great work!

**Comment by hanshuebner** [comment]
@dlxmax The card works well for me and for a couple of people that I've sent it to.  I don't currently have any plans to modify it - I have two RCA jacks connected to the outputs and use active speakers with that.  I don't think that adding an amp would make much sense, as active speakers are the norm nowadays.

**Comment by dlxmax** [comment]
@hanshuebner Excellent. Thank you!
